name: Lint and Type Check

on:
  pull_request:
    branches: [main]  # main 以外のブランチを使っている場合は変更

jobs:
  lint-and-type-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'  # 利用するPythonのバージョンに合わせる

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 mypy
          pip install -r requirements.txt  # 必要なら追加

      - name: Run flake8
        run: flake8 . --max-line-length=88

      - name: Run mypy
        run: mypy .
