name: Lint and Auto Comment

on:
  pull_request:
    branches: [main]

permissions:
  contents: read
  pull-requests: write

jobs:
  lint-and-comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 black mypy
          pip install -r requirements.txt

      # black によるチェック＋自動コメント
      - name: Run Black formatter (check only)
        run: |
          black --check --diff . > black_output.txt || true

      - name: Run flake8
        run: |
          flake8 . --max-line-length=88 > flake8_output.txt || true

      - name: Comment PR with lint results
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: |
            ### Black formatting result:
            ```
            ${{ steps.black.outputs }}
            $(cat black_output.txt)
            ```
            ### Flake8 lint results:
            ```
            $(cat flake8_output.txt)
            ```
