name: Lint and Auto Comment

on:
  pull_request_target:
    branches: [main]

permissions:
  contents: read
  pull-requests: write

jobs:
  lint-and-comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 black mypy
          pip install -r requirements.txt

      - name: Run Black formatter (check only)
        id: black
        run: |
          black --check --diff . > black_output.txt || true
          echo "black_result<<EOF" >> $GITHUB_OUTPUT
          cat black_output.txt >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Run flake8
        id: flake8
        run: |
          flake8 . --max-line-length=88 > flake8_output.txt || true
          echo "flake8_result<<EOF" >> $GITHUB_OUTPUT
          cat flake8_output.txt >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Post PR with lint results
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: |
            ### Black formatting results:
            ```
            ${{ steps.black.outputs.black_result }}
            ```
            
            ### Flake8 lint results:
            ```
            ${{ steps.flake8.outputs.flake8_result }}
            ```
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
