name: Lint, Type Check and Suggest Changes

on:
  pull_request:
    branches: [main]

permissions:
  contents: read
  pull-requests: write

jobs:
  lint-and-suggest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black flake8 mypy
          pip install -r requirements.txt

      - name: Check syntax errors
        run: python -m compileall .

      # Run Black formatter (auto-formatting in runner environment)
      - name: Run Black formatter
        uses: rickstaa/action-black@v1
        id: black_format
        with:
          black_args: "."

      # Suggest formatting fixes on PR if formatting was required
      - name: Suggest Black formatting fixes on PR
        if: steps.black_format.outputs.is_formatted == 'true'
        uses: reviewdog/action-suggester@v1
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.REVIEWDOG_GITHUB_API_TOKEN }}        
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tool_name: black
          level: warning

      - name: Run flake8 linter
        id: flake8-lint
        run: |
          flake8 . --max-line-length=88 --format='::error file=%(path)s,line=%(row)d,col=%(col)d::%(code)s %(text)s' || true

      - name: Run mypy type checker
        id: mypy-check
        run: |
          mypy . --ignore-missing-imports --pretty || true

