name: Lint, Type Check and Suggest Changes

on:
  pull_request:
    branches: [main]

permissions:
  contents: write
  pull-requests: write

jobs:
  lint-and-suggest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black flake8 mypy
          pip install -r requirements.txt

      - name: Check syntax errors
        run: python -m compileall .

      - name: Apply black suggestions to PR
        uses: reviewdog/action-suggester@v1
        with:
          tool_name: black
          fail_level: error
          filter_mode: diff_context

      - name: Run flake8 linter
        id: flake8-lint
        run: |
          flake8 . --max-line-length=88 --format='::error file=%(path)s,line=%(row)d,col=%(col)d::%(code)s %(text)s' || true

      - name: Run mypy type checker
        id: mypy-check
        run: |
          mypy . --ignore-missing-imports --pretty || true
