name: Lint, Type Check and Suggest Changes

on:
  pull_request:
    branches: [main]

permissions:
  contents: write
  pull-requests: write

jobs:
  lint-and-suggest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black flake8 mypy
          pip install -r requirements.txt

      - name: Run black formatter (generate diff)
        id: black-format
        run: |
          black --check --diff . > black_diff.txt || true
          if [ -s black_diff.txt ]; then
            echo "has_diff=true" >> "$GITHUB_OUTPUT"
          else
            echo "has_diff=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Apply black suggestions to PR
        if: steps.black-format.outputs.has_diff == 'true'
        uses: reviewdog/action-suggester@v1
        with:
          tool_name: black
          fail_level: error
          filter_mode: diff_context

      - name: Run flake8 linter
        id: flake8-lint
        run: |
          flake8 . --max-line-length=88 --format='::error file=%(path)s,line=%(row)d,col=%(col)d::%(code)s %(text)s' || true

      - name: Run mypy type checker
        id: mypy-check
        run: |
          mypy . --ignore-missing-imports --pretty || true
